sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
cache: pip
install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip nose numpy
  - source activate test-environment
  - pip install flake8  # Not yet available in Ubuntu precise (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
  - pip install -r requirements.txt
  - pip install --editable .[france,test]
script: bash run-travis-tests.sh
before_deploy:
- python setup.py compile_catalog
- openssl aes-256-cbc -K $encrypted_67b95433b01c_key -iv $encrypted_67b95433b01c_iv
  -in openfisca_bot.enc -out openfisca_bot -d
deploy:
- provider: script
  skip_cleanup: true
  script: ./release-tag.sh
  on:
    branch: master
- provider: pypi
  user: openfisca-bot
  password:
    secure: NTX2IEfW+6m/mVOMevzRYKE9Yo0IumTe/Sxka75c20oJNYsaeoZrI+7132Zm8p+D3yXNqJHgRJTAn5JhMsbJLDf+VjQ0TCZ86/JMc9wZuyvlGCsI5xMJTyj2YTZ6Rdddu3l+4OHUnzelUx/pN8Jt1eYW6CF5PaLUKJtl9tb3X78=
  distributions: "bdist_wheel"
  on:
    tags: true
